export enum RoadmapCategories {
  "DATA_DISCOVERY & COLLABORATION" = "DATA_DISCOVERY & COLLABORATION",
  "DATA INSIGHTS" = "DATA INSIGHTS",
  "DATA QUALITY" = "DATA QUALITY",
  LINEAGE = "LINEAGE",
  "DATA OBSERVABILITY" = "DATA OBSERVABILITY",
  INTEGRATIONS = "INTEGRATIONS",
  SECURITY = "SECURITY",
}
