export const connectorsArr = [
  { name: "Airbyte", icon: "/icons/Connectors/airbyte.png" },
  { name: "Airflow", icon: "./icons/Connectors/airflow.png" },
  { name: "Amazon-s3", icon: "./icons/Connectors/amazon-s3.png" },
  { name: "Amundsen", icon: "./icons/Connectors/amundsen.png" },
  { name: "Athena", icon: "./icons/Connectors/athena.png" },
  { name: "Atlas", icon: "./icons/Connectors/atlas.png" },
  { name: "AzureSQL", icon: "./icons/Connectors/azuresql.png" },
  { name: "BigQuery", icon: "./icons/Connectors/bigquery.png" },
  {
    name: "Clickhouse",
    icon: "./icons/Connectors/clickhouse.png",
  },
  { name: "DataBrick", icon: "./icons/Connectors/databrick.png" },
  { name: "Dbt", icon: "./icons/Connectors/dbt.png" },
  {
    name: "DeltaLake",
    icon: "./icons/Connectors/delta-lake.png",
  },
  { name: "Druid", icon: "./icons/Connectors/druid.png" },
  { name: "DynamoDB", icon: "./icons/Connectors/dynamodb.png" },
  { name: "Glue", icon: "./icons/Connectors/glue.png" },
  {
    name: "GoogleCloud",
    icon: "./icons/Connectors/googleCloudService.png",
  },
  { name: "Hive", icon: "./icons/Connectors/hive.png" },
  { name: "IbmDB", icon: "./icons/Connectors/ibmdb2.png" },
  { name: "Iceberg", icon: "./icons/Connectors/iceberg.png" },
  { name: "Kafka", icon: "./icons/Connectors/kafka.png" },
  { name: "Idap", icon: "./icons/Connectors/idap.png" },
  { name: "Looker", icon: "./icons/Connectors/looker.png" },
  { name: "MariaDB", icon: "./icons/Connectors/mariadb.png" },
  { name: "Metabase", icon: "./icons/Connectors/metabase.png" },
  { name: "MLFlow", icon: "./icons/Connectors/mlflow.png" },
  { name: "Mode", icon: "./icons/Connectors/mode.png" },
  { name: "Mssql", icon: "./icons/Connectors/mssql.png" },
  { name: "Oracle", icon: "./icons/Connectors/oracle.png" },
  { name: "Pinot", icon: "./icons/Connectors/pinot.png" },
  { name: "Post", icon: "./icons/Connectors/post.png" },
  { name: "PowerBI", icon: "./icons/Connectors/power-bi.png" },
  { name: "Presto", icon: "./icons/Connectors/presto.png" },
  { name: "Pulsar", icon: "./icons/Connectors/pulsar.png" },
  { name: "Redash", icon: "./icons/Connectors/redash.png" },
  { name: "Redshift", icon: "./icons/Connectors/redshift.png" },
  {
    name: "SalesForce",
    icon: "./icons/Connectors/salesforce.png",
  },
  {
    name: "SingleStore",
    icon: "./icons/Connectors/singlestore.png",
  },
  {
    name: "Snowflake",
    icon: "./icons/Connectors/snowflakes.png",
  },
  { name: "SQL", icon: "./icons/Connectors/sql.png" },
  {
    name: "SqlAlchemy",
    icon: "./icons/Connectors/sqlalchemy.png",
  },
  { name: "Sqlite", icon: "./icons/Connectors/sqlite.png" },
  { name: "Superset", icon: "./icons/Connectors/superset.png" },
  { name: "Tableau", icon: "./icons/Connectors/tableau.png" },
  { name: "Trino", icon: "./icons/Connectors/trino.png" },
  { name: "Vertica", icon: "./icons/Connectors/vertica.png" },
];
