export const connectorsArr = [
  { name: "Airbyte", icon: "./images/connectors/airbyte.png" },
  { name: "Airflow", icon: "./images/connectors/airflow.png" },
  { name: "Amazon-s3", icon: "./images/connectors/amazon-s3.png" },
  { name: "Amundsen", icon: "./images/connectors/amundsen.png" },
  { name: "Athena", icon: "./images/connectors/athena.png" },
  { name: "Atlas", icon: "./images/connectors/atlas.png" },
  { name: "AzureSQL", icon: "./images/connectors/azuresql.png" },
  { name: "BigQuery", icon: "./images/connectors/bigquery.png" },
  {
    name: "Clickhouse",
    icon: "./images/connectors/clickhouse.png",
  },
  { name: "DataBrick", icon: "./images/connectors/databrick.png" },
  { name: "Dbt", icon: "./images/connectors/dbt.png" },
  {
    name: "DeltaLake",
    icon: "./images/connectors/delta-lake.png",
  },
  { name: "Druid", icon: "./images/connectors/druid.png" },
  { name: "DynamoDB", icon: "./images/connectors/dynamodb.png" },
  { name: "Glue", icon: "./images/connectors/glue.png" },
  {
    name: "GoogleCloud",
    icon: "./images/connectors/googleCloudService.png",
  },
  { name: "Hive", icon: "./images/connectors/hive.png" },
  { name: "IbmDB", icon: "./images/connectors/ibmdb2.png" },
  { name: "Iceberg", icon: "./images/connectors/iceberg.png" },
  { name: "Kafka", icon: "./images/connectors/kafka.png" },
  { name: "Looker", icon: "./images/connectors/looker.png" },
  { name: "MariaDB", icon: "./images/connectors/mariadb.png" },
  { name: "Metabase", icon: "./images/connectors/metabase.png" },
  { name: "MLFlow", icon: "./images/connectors/mlflow.png" },
  { name: "Mode", icon: "./images/connectors/mode.png" },
  { name: "Mssql", icon: "./images/connectors/mssql.png" },
  { name: "Oracle", icon: "./images/connectors/oracle.png" },
  { name: "Pinot", icon: "./images/connectors/pinot.png" },
  { name: "Post", icon: "./images/connectors/post.png" },
  { name: "PowerBI", icon: "./images/connectors/power-bi.png" },
  { name: "Presto", icon: "./images/connectors/presto.png" },
  { name: "Redash", icon: "./images/connectors/redash.png" },
  { name: "Redshift", icon: "./images/connectors/redshift.png" },
  {
    name: "SalesForce",
    icon: "./images/connectors/salesforce.png",
  },
  {
    name: "SingleStore",
    icon: "./images/connectors/singlestore.png",
  },
  {
    name: "Snowflake",
    icon: "./images/connectors/snowflakes.png",
  },
  { name: "SQL", icon: "./images/connectors/sql.png" },
  {
    name: "SqlAlchemy",
    icon: "./images/connectors/sqlalchemy.png",
  },
  { name: "Sqlite", icon: "./images/connectors/sqlite.png" },
  { name: "Superset", icon: "./images/connectors/superset.png" },
  { name: "Tableau", icon: "./images/connectors/tableau.png" },
  { name: "Trino", icon: "./images/connectors/trino.png" },
  { name: "Vertica", icon: "./images/connectors/vertica.png" },
];
